sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: sky
    password: 203314wa.

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx63ecef51c9ddd2ab
    secret: 88379808036ff71880acceaf0bc96f86